import { EvaluatedSequence } from '../types/simulation'
import { SheetMetalPart, Material } from '../types/sheetMetal'
import { Punch, Die } from '../types/tooling'
import { DelemPartProgram, DelemProgramStep } from '../types/delem'

export function generateDelemProgram(
  part: SheetMetalPart,
  material: Material,
  sequence: EvaluatedSequence,
  punch: Punch,
  die: Die,
  flatBlankLength: number
): DelemPartProgram {
  let prevOrientation = 'FORWARD'

  const steps: DelemProgramStep[] = sequence.steps.map((step, idx) => {
    let partTurn = 'Normal'
    if (idx > 0 && step.orientation !== prevOrientation) {
      partTurn = 'Turn 180°'
    }
    prevOrientation = step.orientation

    return {
      step: idx + 1,
      bendNumber: step.bendIndex + 1,
      angle: step.targetAngle,
      opening: 80.0, // standard clamp opening
      yAxis: step.ramStrokeY,
      xAxis: step.gaugeX,
      rAxis: step.gaugeR,
      crowning: step.crowningValue,
      forceTonnes: step.tonnageTonnes,
      punchName: punch.name,
      dieName: die.name,
      partTurn,
    }
  })

  return {
    programName: part.name.toUpperCase().replace(/\s+/g, '_'),
    controller: 'DELEM DA-53T',
    thickness: part.thickness,
    material: material.name,
    blankLength: flatBlankLength,
    bendLength: part.width,
    totalSteps: steps.length,
    steps,
  }
}

export function exportDelemTextReport(program: DelemPartProgram): string {
  const line = '='.repeat(78)
  const subLine = '-'.repeat(78)

  let txt = `${line}\n`
  txt += `  DELEM DA-53T CNC PRESS BRAKE BEND PROGRAM\n`
  txt += `  Program Name : ${program.programName}\n`
  txt += `  Controller   : ${program.controller}\n`
  txt += `  Material     : ${program.material} | Thickness: ${program.thickness} mm\n`
  txt += `  Blank Length : ${program.blankLength} mm | Bend Width: ${program.bendLength} mm\n`
  txt += `  Total Bends  : ${program.totalSteps}\n`
  txt += `${line}\n`
  txt += `STEP | BEND# | ANGLE(°) | Y-AXIS(mm) | X-GAUGE(mm) | R-AXIS | TONNES | PART TURN\n`
  txt += `${subLine}\n`

  for (const s of program.steps) {
    const stepStr = s.step.toString().padStart(4, ' ')
    const bendStr = s.bendNumber.toString().padStart(5, ' ')
    const angleStr = s.angle.toFixed(1).padStart(8, ' ')
    const yStr = s.yAxis.toFixed(2).padStart(10, ' ')
    const xStr = s.xAxis.toFixed(1).padStart(11, ' ')
    const rStr = s.rAxis.toFixed(1).padStart(6, ' ')
    const tonStr = s.forceTonnes.toFixed(1).padStart(6, ' ')
    const turnStr = s.partTurn.padEnd(10, ' ')

    txt += `${stepStr} | ${bendStr} | ${angleStr} | ${yStr} | ${xStr} | ${rStr} | ${tonStr} | ${turnStr}\n`
  }

  txt += `${line}\n`
  txt += `Generated by Antigravity Sheet Metal Bending Simulator\n`
  return txt
}
